#!/usr/bin/env sh

background() {
  while :; do
    mix run -e 'Philomena.Release.update_channels()'
    mix run -e 'Philomena.Release.verify_artist_links()'
    mix run -e 'Philomena.Release.update_stats()'

    sleep 300
  done
}

# Always install assets
(
cd /srv/philomena/assets
# workaround for #31
npm install || (chown -R root:root node_modules && npm install)
)

# Always install mix dependencies
(cd /srv/philomena && mix deps.get)

# Sleep to allow Elasticsearch to finish initializing
# if it's not done doing whatever it does yet
echo -n "Waiting for Elasticsearch"

until wget -qO - elasticsearch:9200; do
  echo -n "."
  sleep 2
done

echo

# Try to create the database if it doesn't exist yet
createdb -h postgres -U postgres philomena_dev && mix ecto.setup_dev && mix reindex_all

# Run background jobs
background &

str=`date -Ins | md5sum`
echo str
echo $str
#name=${str:0:10}
name="e2e2ae9ba4"

# Run the application
#START_WORKER=true exec iex --cookie chocochip --name remote@192.168.1.124 --erl '-kernel inet_dist_listen_min 9000' --erl '-kernel inet_dist_listen_max 9000' -S mix phx.server
#START_WORKER=true exec elixir --sname $name --cookie chocochip -S mix phx.server
START_WORKER=true exec x11vnc -forever -usepw -create
